name: "Scrap workflow"

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrap:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: "Setup headless display"
        uses: pyvista/setup-headless-display-action@v2

      - name: "Install Chrome"
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      
      - name: "Install dependencies"
        run: go mod download

      - name: "Scrap"
        run: go run cmd/scraper/main.go

      - name: "Configure git"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: "Commit changes (on data branch)"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git checkout data || git checkout -b data
          git add -f "matches.json"
          git commit -m "update matches.json"
          git push -u origin data